### ISSUE TITLE
Give different username for different projects on server

### ISSUE THREAD

**Issue by tq5124** [bicCluster/docs#1]
I think that would be much more easier to manage than all of us using the same username `bicadmin`
1. different user has different home folder
2. different user has different command history
3. one users cannot rm other`s files

**Comment by CodeMySky** [comment]
I agree, I created this page [Username Assignmens](https://github.com/bicCluster/docs/wiki/Username-Assignments)
We should work on this.

**Comment by CodeMySky** [comment]
Most of the projects now have a username.
