### ISSUE TITLE
Gitlab down

### ISSUE THREAD

**Issue by tq5124** [bicCluster/docs#5]

**Comment by tq5124** [comment]
<img width="435" alt="screen shot 2015-11-13 at 8 22 24 pm" src="https://cloud.githubusercontent.com/assets/4020127/11161199/488cd798-8a44-11e5-8104-6518f697c42c.png">

@CodeMySky , someone run a mapper and used up the driver space?

**Comment by tq5124** [comment]
<img width="535" alt="screen shot 2015-11-13 at 8 36 55 pm" src="https://cloud.githubusercontent.com/assets/4020127/11161275/56983c5e-8a46-11e5-808b-a3a11d3b7bbf.png">

It seems like someone named "guans" start a mapper yesterday and occupy all the file system

**Comment by CodeMySky** [comment]
<img width="384" alt="screen shot 2015-11-13 at 9 18 40 pm" src="https://cloud.githubusercontent.com/assets/1545856/11161491/33479adc-8a4c-11e5-9b9d-faf672dd13fe.png">

**Comment by tq5124** [comment]
I think the path should be /dev/mapper/centos-root. Now that someone remove the files and the usage come down to 39%. Gitlab works now

**Comment by CodeMySky** [comment]
I removed zookeeper log, and killed zookeeper process.
<img width="431" alt="screen shot 2015-11-13 at 9 22 31 pm" src="https://cloud.githubusercontent.com/assets/1545856/11161514/b0178234-8a4c-11e5-8d73-768782c63c6e.png">
